### ISSUE TITLE
Reposition the focus

### ISSUE THREAD

**Issue by Melir91** [manuelstofer/pinchzoom#101] opened 2019-08-16 08:02 UTC
Hello, I update the image src in onZoomStart callback with bigger image resolution which cause me an unwanted repositioning, does anybody have any ideas how to handle this?

**Comment by sandstrom** [comment] 2019-08-21 09:01
Is this an issue with the code itself, or a general question? For general questions [Stackoverflow](https://stackoverflow.com/) is better than Github.

I'm closing this now, but I'm willing to reopen if there is an actual code issue. If so, steps to reproduce (and ideally a failing test-case) is a good start. 

Since this is an open-source project there is no one paid to work on it, so if you want it to change it's usually a good idea to contribute the code.

**Closed by sandstrom** 2019-08-21 09:01 UTC
