### ISSUE TITLE
Images and text appear blurred

### ISSUE THREAD

**Issue by creativesplash** [manuelstofer/pinchzoom#65] opened 2018-06-13 16:38 UTC
Hello there!

Thanks once again for this fantastic plugin! My images and text appear blurred when I zoom in. Any ideas what could be happening?

Thanks,
Vasanth

**Comment by sandstrom** [comment] 2018-06-14 09:42
No idea 😄 

This is open source code, unfortunately we cannot offer general troubleshooting. But if you think you've found a bug, and a way to fix it, we're happy to accept a PR with a fix.

A simple reproduction or the issue is usually a good start.

**Comment by sandstrom** [comment] 2018-10-12 13:50
I'm going to close this issue. Happy to review a PR if anyone has found a reproducible bug.

**Closed by sandstrom** 2018-10-12 13:50 UTC
